---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: podman

platforms:

  - name: test-in-fedora
    image: fedora_molecule
    privileged: true
    pre_build_image: true

  # - name: test-in-ubuntu
  #   image: ubuntu:latest
  #   privileged: true
  #   pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callbacks: yaml
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
